version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run:
          name: Clean Build Directory
          command: './clean.sh'
      - run:
          name: Run Build Script
          command: './build.sh'

  build_artifact:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Clean Build Directory
          command: './clean.sh'
      - run:
          name: Run Build Script
          command: './build.sh'
      - store_artifacts:
          path: builds
          prefix: build

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - build_artifact:
          filters:
            branches:
              only: master
